### ISSUE TITLE
请问你的站点既然是Vue写的，为什么源代码里面有内容？

### ISSUE THREAD

**Issue by 158008001** [qinvz/qinmeivideo#2]
你是怎么实现静态化的，而不是只有一段script的代码？

**Comment by qinvz** [comment]
.......vue不就是这样的吗, 数据驱动视图

**Comment by 158008001** [comment]
并没有用ssr？没用服务器解析吗？
致使你干了一件了不起的事情都毫不知情。。。

**Comment by qinvz** [comment]
.......我还没上线,后台全都是PHP的,鬼知道你说的是哪个网站

**Comment by 158008001** [comment]
没上线，难道不是这个：https://qinmei.video

**Comment by 158008001** [comment]
这个网站确实漂亮啊
