### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by Nekoer** [qinvz/qinmeivideo#3]
![n eqo xwqghid25 ao8nf2](https://user-images.githubusercontent.com/32485369/46857140-d8787c80-ce3a-11e8-8849-811d4c1250fb.png)
请问大佬这个该怎么处理

![wrj_6t35c_gjxdm 9_gq458](https://user-images.githubusercontent.com/32485369/46857218-0362d080-ce3b-11e8-90bd-ba8ac2e27ec3.png)
还有用户面板好像有问题，前台头像也传不了

**Comment by qinvz** [comment]
把详细的报错信息贴上来，另外用户头像的上传需要自己新建个普通用户，管理员是无法进行上传的

**Comment by Nekoer** [comment]
Warning : Use of undefined constant page - assumed 'page' (this will throw an Error in a future version of PHP) in
/www/wwwroot/tv.hcyacg.com/wp-content/themes/qinmei/page-pc/page/discuss.php
on line 455

**Comment by Nekoer** [comment]
啊，好了，是php版本的问题，我用了7.2版本
