### ISSUE TITLE
视频选集，个人资料页的一些报错

### ISSUE THREAD

**Issue by yk2008ok** [qinvz/qinmeivideo#4]
暂时没有电脑，不过个人资料页的报错让我很是纳闷。
![Uploading Screenshot_2018-10-17-23-17-42-001_com.android.chrome.png…]()
![screenshot_2018-10-17-23-20-06-063_com android chrome](https://user-images.githubusercontent.com/31175416/47097087-37872880-d263-11e8-8be0-5dc6863fdc3a.png)

**Comment by yk2008ok** [comment]
已关闭，不过qinmei主题设置中，"更新动漫"选项打开会提示The link you followed has expired.
而"创建页面"打开则是空白页。
![img_20181018_003159](https://user-images.githubusercontent.com/31175416/47101662-496dc900-d26d-11e8-990d-84dc51d7b43d.jpg)

**Comment by yk2008ok** [comment]
还有就是，我设置了REwrite规则后，基础页面正常显示，可这些仍报404
![img_20181018_003845](https://user-images.githubusercontent.com/31175416/47102083-59d27380-d26e-11e8-9c96-7560acbbfc81.jpg)

**Comment by qinvz** [comment]
更新动漫需要的是我这边提供的远程接口，自然无法使用，忘记删除了。

创建页面这个并没有什么输出，直接去后台看页面有没有创建就好，没有的话自己手动创建就是了。

报错是因为没有按照说明正确的设置分类以及类型，按照说明一个个对比是否缺少了某些项

**Comment by yk2008ok** [comment]
请问一下如何添加播放地址= =|||

**Comment by qinvz** [comment]
内容区域放直链

**Comment by yk2008ok** [comment]
我刚刚对比文件时，发现我的主题目录里与GIT里少了font/fontawesome这个文件夹。见鬼。

**Comment by qinvz** [comment]
设置解析接口啊，怎么可能直接播放

**Comment by yk2008ok** [comment]
![img_20181020_004631](https://user-images.githubusercontent.com/31175416/47232186-9b475800-d401-11e8-9255-5d67ae4ca4ee.jpg)
很早就设置过了哦

**Comment by yk2008ok** [comment]
能给一下播放列表的设置截图嘛？万分感谢(◦˙▽˙◦)

**Comment by qinvz** [comment]
这版本早就不用了，只能你自己看了

**Comment by yk2008ok** [comment]
![img_20181020_010814](https://user-images.githubusercontent.com/31175416/47233286-c4b5b300-d404-11e8-90e9-4fbe24b3e085.jpg)
感觉这样绝对是错的。。。

**Comment by qinvz** [comment]
。。。。想起来了，下面有剧集信息啊，标题连接啥的自己放进去啊

**Comment by yk2008ok** [comment]
可以了，不过直链如何调用onedrive上的资源?尝试使用onedrive直链会报错

**Comment by yk2008ok** [comment]
获取直链是属于那种直接访问会下载，加个vedio标签就能引用播放的那种。。。

**Comment by qinvz** [comment]
随便创建一篇文章发布

**Comment by yk2008ok** [comment]
![img_20181022_004533](https://user-images.githubusercontent.com/31175416/47269731-9ebf1880-d594-11e8-8252-eaf3ec61d00b.jpg)
已解决，但这几个目录我实在是不知道该怎么设置伪静态了。。。
找不到实际路径

**Comment by yk2008ok** [comment]
![img_20181022_004533](https://user-images.githubusercontent.com/31175416/47269758-eba2ef00-d594-11e8-811c-7ef8b966679b.jpg)

**Comment by yk2008ok** [comment]
另外有个奇怪的问题。
手机版播放时，播放器似乎获取不到播放地址。
PC版却正常播放。
![img_20181022_023507](https://user-images.githubusercontent.com/31175416/47270778-362b6800-d5a3-11e8-9ea2-bd8da0a4643a.jpg)
![img_20181022_023453](https://user-images.githubusercontent.com/31175416/47270784-4f341900-d5a3-11e8-8b6e-03a273c099bd.jpg)

**Comment by yk2008ok** [comment]
虽然我对PHP不那么了解，但还是解决了。
PC版与手机版，播放器url调用时出错。
原因来自手机版play.php
第809行
将其改成
url: '<?php echo $meta_value[$sort]['baseinfo_episode_link'];?>',
即可正常获取播放url

**Comment by yk2008ok** [comment]
无法设置视频查阅权限。。。
